In [3]:

for i in range(10):
    #print(i)
    print(i%2)

0
1
0
1
0
1
0
1
0
1


In [15]:
import numpy as np
from scipy import signal

arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
G_conv = np.array([[0, 1, 0], [1, 0, 1], [0, 1, 0]]) / 4
print(signal.convolve2d(arr, G_conv, 'valid')[0][0])

arr_2 = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr_3 = np.array([arr, arr_2])
print(arr_3.shape)

5.0
(2, 3, 3)


In [13]:
img = np.zeros((3, 3))
print(img)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [16]:
import os
import cv2

path = "/Users/qiaowenyang/Desktop/22ss/jssxx/labs/Codingproject/inputs/Demosaicing"
def process(path):
    for file in os.listdir(path):
        filename = os.path.join(path, file)
        #img_plt = plt.imread(filename)
        
        
        img = cv2.imread(filename)
        print(f"shape: {img.shape}")
        print(f"{file} before demosaicing:")
        #cv2.imshow(f"{file}", img)
        #cv2.waitKey(3000)
        
        print(img[:, :, 0])
        print(img[:, :, 1])
        print(img[:, :, 2])
        img_cfa = img[:, :, 0] + img[:, :, 1] + img[:, :, 2]
        print(img_cfa)
        #img_d = Bilinear_Demosaicing(img_cfa)
        #print(f"{file} after demosaicing:")
        #cv2.imshow(f"demosaicing_{file}", img_d)
        #cv2.waitKey(3000)
        #cv2.destroyAllWindows()
        

process(path)

shape: (500, 500, 3)
8.png before demosaicing:
[[  0   0   0 ...   0   0   0]
 [  3   0   2 ...   0  51   0]
 [  0   0   0 ...   0   0   0]
 ...
 [  6   0  19 ...   0 162   0]
 [  0   0   0 ...   0   0   0]
 [ 18   0  57 ...   0 185   0]]
[[  6   0   4 ...   0  52   0]
 [  0   3   0 ...  50   0  50]
 [  6   0   5 ...   0  58   0]
 ...
 [  0  20   0 ... 207   0 206]
 [ 42   0  43 ...   0 214   0]
 [  0 142   0 ... 203   0 215]]
[[  0   1   0 ...  51   0  49]
 [  0   0   0 ...   0   0   0]
 [  0   1   0 ...  53   0  54]
 ...
 [  0   0   0 ...   0   0   0]
 [  0  79   0 ... 213   0 192]
 [  0   0   0 ...   0   0   0]]
[[  6   1   4 ...  51  52  49]
 [  3   3   2 ...  50  51  50]
 [  6   1   5 ...  53  58  54]
 ...
 [  6  20  19 ... 207 162 206]
 [ 42  79  43 ... 213 214 192]
 [ 18 142  57 ... 203 185 215]]
shape: (500, 500, 3)
9.png before demosaicing:
[[ 0  0  0 ...  0  0  0]
 [ 5  0  8 ...  0 21  0]
 [ 0  0  0 ...  0  0  0]
 ...
 [46  0 40 ...  0 46  0]
 [ 0  0  0 ...  0  0  0]
 [47  0 